### ISSUE TITLE
Master is not in sync with https://odahub.io/docs

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/hugo-odahub#79]
Julia reported the broken link in https://odahub.io/docs/guide-development/#handling-exceptions

Trying to fix it, I noticed there is no such section in https://github.com/oda-hub/hugo-odahub/blob/master/content/docs/guide-development.md

Which branch is actually got built (there are no github workflow configs here) ?

**Comment by volodymyrss** [comment]
what's synced is [this other repo](https://github.com/oda-hub/oda-hub.github.io/) while the source in this current repo is synced with a separate controller which also has access to some private and network-restricted resources with ontology like webprotege (hence not accessible from github actions). However, since we now just github ontology as primary tracker, this can be simplified.

For now, I fixed the sync.

**Comment by dsavchenko** [comment]
Also, many changes are in https://github.com/oda-hub/hugo-odahub/pull/67 but not in master, probably that's the reason why rendered documentation was synced with other branch...

**Comment by volodymyrss** [comment]
It should be in-sync now, and the action is updated to maintain it better. Please reopen if needed.
